{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sensorbio",
    "module": "sensorbio-sdk",
    "version": "0.14.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "publicReleaseVariantPublicReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sensorbio-sdk-0.14.1.aar",
          "url": "sensorbio-sdk-0.14.1.aar",
          "size": 12362464,
          "sha512": "68e90526515eb7ada555ec12127cf9410d7a8fa2c8b3cf8cc8f13f9771d1c51077a2ea3cab33d5bffd11c171f15e4f4fb99db0fc281f6e5ce76a6ba5aee7d3b4",
          "sha256": "2990b237e4cf27a5c8339ac2a6ee63ce8b95d6aece4fc8b9eeee3313a16c12ef",
          "sha1": "d8c16914b47cc745463fcef2f6709299e5dda4e0",
          "md5": "3ddbd2291e8698b3259534720cc6d152"
        }
      ]
    },
    {
      "name": "publicReleaseVariantPublicReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.10"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.2"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.2"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.3"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.3"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "org.eclipse.paho",
          "module": "org.eclipse.paho.client.mqttv3",
          "version": {
            "requires": "1.2.5"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.14.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "com.jakewharton",
          "module": "disklrucache",
          "version": {
            "requires": "2.0.2"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.3"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.7"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.32.1"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf-lite",
          "version": {
            "requires": "1.75.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "io.grpc",
          "module": "grpc-core",
          "version": {
            "requires": "1.75.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "io.grpc",
          "module": "grpc-okhttp",
          "version": {
            "requires": "1.75.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.75.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "io.grpc",
          "module": "grpc-android",
          "version": {
            "requires": "1.75.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sensorbio-sdk-0.14.1.aar",
          "url": "sensorbio-sdk-0.14.1.aar",
          "size": 12362464,
          "sha512": "68e90526515eb7ada555ec12127cf9410d7a8fa2c8b3cf8cc8f13f9771d1c51077a2ea3cab33d5bffd11c171f15e4f4fb99db0fc281f6e5ce76a6ba5aee7d3b4",
          "sha256": "2990b237e4cf27a5c8339ac2a6ee63ce8b95d6aece4fc8b9eeee3313a16c12ef",
          "sha1": "d8c16914b47cc745463fcef2f6709299e5dda4e0",
          "md5": "3ddbd2291e8698b3259534720cc6d152"
        }
      ]
    }
  ]
}
