{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sensorbio",
    "module": "sensorbio-sdk",
    "version": "0.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "publicReleaseVariantPublicReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sensorbio-sdk-0.13.0.aar",
          "url": "sensorbio-sdk-0.13.0.aar",
          "size": 12364686,
          "sha512": "1577ae815988451e115499e6d855776157541349c777022c3af7cf2dd2ec495e54ecb545358646678f68adde94224e14f220c5a2e55e811e4ad27b333c63e948",
          "sha256": "08e774d3027f818d115f7a60d80f5f4da5f2be1bff82fe0f7f01f1facd3593f7",
          "sha1": "aa8925ccbb7de2903375d4707fecd043f86bc55c",
          "md5": "53f9292d169f011a42107c0b53114323"
        }
      ]
    },
    {
      "name": "publicReleaseVariantPublicReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.10"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.2"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.2"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.3"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.3"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "org.eclipse.paho",
          "module": "org.eclipse.paho.client.mqttv3",
          "version": {
            "requires": "1.2.5"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.14.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "com.jakewharton",
          "module": "disklrucache",
          "version": {
            "requires": "2.0.2"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.3"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.7"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.32.1"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf-lite",
          "version": {
            "requires": "1.75.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "io.grpc",
          "module": "grpc-core",
          "version": {
            "requires": "1.75.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "io.grpc",
          "module": "grpc-okhttp",
          "version": {
            "requires": "1.75.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.75.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "io.grpc",
          "module": "grpc-android",
          "version": {
            "requires": "1.75.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sensorbio-sdk-0.13.0.aar",
          "url": "sensorbio-sdk-0.13.0.aar",
          "size": 12364686,
          "sha512": "1577ae815988451e115499e6d855776157541349c777022c3af7cf2dd2ec495e54ecb545358646678f68adde94224e14f220c5a2e55e811e4ad27b333c63e948",
          "sha256": "08e774d3027f818d115f7a60d80f5f4da5f2be1bff82fe0f7f01f1facd3593f7",
          "sha1": "aa8925ccbb7de2903375d4707fecd043f86bc55c",
          "md5": "53f9292d169f011a42107c0b53114323"
        }
      ]
    }
  ]
}
