{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sensorbio",
    "module": "sensorbio-sdk",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "publicReleaseVariantPublicReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sensorbio-sdk-1.1.0.aar",
          "url": "sensorbio-sdk-1.1.0.aar",
          "size": 12605651,
          "sha512": "2b17dbf0c4e6e0829d596bc6c45692190f3c740a42475ccc7d004933f3923a641312043f28d5bd5540f7c30f67e654f090274312a5f6b79b8c5856b66bd95b8b",
          "sha256": "9abde747ddb634a7bd686829c7f1ec998d9464ce94f830805bb70a1d0f3fc7f0",
          "sha1": "13d381cde1df30ab2106eafde129e28e3c0a6071",
          "md5": "eb501065aa8690b1694de793bdc4fc0a"
        }
      ]
    },
    {
      "name": "publicReleaseVariantPublicReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.10"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.2"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.2"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.3"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.3"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "org.eclipse.paho",
          "module": "org.eclipse.paho.client.mqttv3",
          "version": {
            "requires": "1.2.5"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.14.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "com.jakewharton",
          "module": "disklrucache",
          "version": {
            "requires": "2.0.2"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.3"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.7"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.32.1"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf-lite",
          "version": {
            "requires": "1.75.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "io.grpc",
          "module": "grpc-core",
          "version": {
            "requires": "1.75.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "io.grpc",
          "module": "grpc-okhttp",
          "version": {
            "requires": "1.75.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.75.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "io.grpc",
          "module": "grpc-android",
          "version": {
            "requires": "1.75.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sensorbio-sdk-1.1.0.aar",
          "url": "sensorbio-sdk-1.1.0.aar",
          "size": 12605651,
          "sha512": "2b17dbf0c4e6e0829d596bc6c45692190f3c740a42475ccc7d004933f3923a641312043f28d5bd5540f7c30f67e654f090274312a5f6b79b8c5856b66bd95b8b",
          "sha256": "9abde747ddb634a7bd686829c7f1ec998d9464ce94f830805bb70a1d0f3fc7f0",
          "sha1": "13d381cde1df30ab2106eafde129e28e3c0a6071",
          "md5": "eb501065aa8690b1694de793bdc4fc0a"
        }
      ]
    }
  ]
}
