{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sensorbio",
    "module": "sensorbio-sdk",
    "version": "0.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "publicReleaseVariantPublicReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sensorbio-sdk-0.10.0.aar",
          "url": "sensorbio-sdk-0.10.0.aar",
          "size": 12332735,
          "sha512": "091e814921e100562ef88afb0de5e6ec9099412d3c361c0d1dd98bb98832837808f458a5879b1290dd784f4cf7527035203905d061e9d110eca03c7d49784870",
          "sha256": "037c8ad613fedc75f299cefb8955d633474b611f885f6502d73d2b609c2bcbcb",
          "sha1": "1c0949a29b9e7c00a6e39ac12231baa2533fd8d2",
          "md5": "0c745983c95116903f421b5b4912ac06"
        }
      ]
    },
    {
      "name": "publicReleaseVariantPublicReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.10"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.2"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.2"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.3"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.3"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "org.eclipse.paho",
          "module": "org.eclipse.paho.client.mqttv3",
          "version": {
            "requires": "1.2.5"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.14.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "com.jakewharton",
          "module": "disklrucache",
          "version": {
            "requires": "2.0.2"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.3"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.7"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.32.1"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf-lite",
          "version": {
            "requires": "1.75.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "io.grpc",
          "module": "grpc-core",
          "version": {
            "requires": "1.75.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "io.grpc",
          "module": "grpc-okhttp",
          "version": {
            "requires": "1.75.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.75.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "io.grpc",
          "module": "grpc-android",
          "version": {
            "requires": "1.75.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sensorbio-sdk-0.10.0.aar",
          "url": "sensorbio-sdk-0.10.0.aar",
          "size": 12332735,
          "sha512": "091e814921e100562ef88afb0de5e6ec9099412d3c361c0d1dd98bb98832837808f458a5879b1290dd784f4cf7527035203905d061e9d110eca03c7d49784870",
          "sha256": "037c8ad613fedc75f299cefb8955d633474b611f885f6502d73d2b609c2bcbcb",
          "sha1": "1c0949a29b9e7c00a6e39ac12231baa2533fd8d2",
          "md5": "0c745983c95116903f421b5b4912ac06"
        }
      ]
    }
  ]
}
